In [6]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, multilabel_confusion_matrix
import models
import process_data
import analysis
import train_mi

In [7]:
#setup
BATCH_SIZE = 200
LEARNING_RATE = 0.0005
NUM_EPOCHS = 25
device ='cpu'
device_count = 0
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device_count = torch.cuda.device_count()


In [8]:
cnetmodel1 = models.get_model("cnet")
cnetmodel1.load_state_dict(torch.load("cnetmodele20"))

<All keys matched successfully>

In [9]:
mimodel = models.transfer_model(cnetmodel1, freeze_params=False)

In [10]:
train_loadermi, val_loadermi = process_data.load_data_mi(batch_size=BATCH_SIZE)

In [11]:
criterion1 = nn.BCELoss()
optimizer1 = torch.optim.Adam(mimodel.parameters(), lr=0.001)


In [12]:
train_mi.train(mimodel, train_loadermi, val_loadermi, 20, criterion1, optimizer1)

Epoch: 1 	 Training Loss: 0.411193
Epoch: 1 	 Validation f: 0.8083, acc: 0.8660
[[ 462  347]
 [  43 2059]]
Epoch: 2 	 Training Loss: 0.230880
Epoch: 2 	 Validation f: 0.9185, acc: 0.9358
[[ 692  117]
 [  70 2032]]
Epoch: 3 	 Training Loss: 0.133429
Epoch: 3 	 Validation f: 0.9504, acc: 0.9605
[[ 741   68]
 [  47 2055]]
Epoch: 4 	 Training Loss: 0.083579
Epoch: 4 	 Validation f: 0.9547, acc: 0.9626
[[ 795   14]
 [  95 2007]]
Epoch: 5 	 Training Loss: 0.056129
Epoch: 5 	 Validation f: 0.9771, acc: 0.9818
[[ 772   37]
 [  16 2086]]
Epoch: 6 	 Training Loss: 0.051705
Epoch: 6 	 Validation f: 0.9588, acc: 0.9681
[[ 719   90]
 [   3 2099]]
Epoch: 7 	 Training Loss: 0.042838
Epoch: 7 	 Validation f: 0.9698, acc: 0.9753
[[ 799   10]
 [  62 2040]]
Epoch: 8 	 Training Loss: 0.031849
Epoch: 8 	 Validation f: 0.9858, acc: 0.9887
[[ 783   26]
 [   7 2095]]
Epoch: 9 	 Training Loss: 0.025558
Epoch: 9 	 Validation f: 0.9545, acc: 0.9650
[[ 707  102]
 [   0 2102]]
Epoch: 10 	 Training Loss: 0.027103
E

In [37]:
(2040+724)/(2040+724+85+62)

0.9495018893850911